# Utilisation de l'image Nginx Alpine (légère)
FROM nginx:alpine

# Définir le répertoire de travail
WORKDIR /usr/share/nginx/html

# Copier les fichiers frontend dans le conteneur
COPY . .

# Exposer le port 80
EXPOSE 80