# Utiliser l'image nginx pour servir les fichiers statiques
FROM nginx:alpine

# Copier les fichiers de l'application dans le dossier de serveur web
COPY . /usr/share/nginx/html/

# Exposer le port 80
EXPOSE 80
